=== Hager-Abd-El-Galil/ITI_OpenSourceApplicationDevelopment/XML Fundamentals/Lab2/employees/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (employee*)>
<!ELEMENT employee (name, phones, addresses, email)>
<!ATTLIST employee isbn CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT addresses (address)>
<!ELEMENT address (Street,BuildingNumber,Region,City,Country)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT BuildingNumber (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== Hager-Abd-El-Galil/ITI_OpenSourceApplicationDevelopment/XML Fundamentals/Lab2/employees/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM 'employee.dtd'>
<?xml-stylesheet type="text/css" href="./employee.css" ?>

<employees>
    <!--Employee One-->
    <employee isbn="1">
        <name>Ahmed Ali</name>
        <phones>
            <phone type="home">035611296</phone>
        </phones>
        <addresses>
            <address>
                <Street>119 st</Street>
                <BuildingNumber>6</BuildingNumber>
                <Region>ElMaamora</Region>
                <City>Alexandria</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>Ahmed@gmail.com</email>
    </employee>

    <!--Employee Two-->
    <employee isbn="2">
        <name>Amr Hesham</name>
        <phones>
            <phone type="home">035411096</phone>
        </phones>
        <addresses>
            <address>
                <Street>268 st</Street>
                <BuildingNumber>7</BuildingNumber>
                <Region>Miami</Region>
                <City>Alexandria</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>Amr@gmail.com</email>
    </employee>

    <!--Employee Three-->
    <employee isbn="3">
        <name>Alaa Ahmed</name>
        <phones>
            <phone type="home">035511060</phone>
        </phones>
        <addresses>
            <address>
                <Street>El hosary st</Street>
                <BuildingNumber>6</BuildingNumber>
                <Region>6 October</Region>
                <City>Cairo</City>
                <Country>Eqypt</Country>
            </address>
        </addresses>
        <email>Alaa@gmail.com</email>
    </employee>
    
</employees>
